version: '3.8'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    volumes:
      - D:/assignment/solution/inputFile:/csvserver/inputdata
    env_file:
      - csvserver.env
    restart: always

